/**
 * Public OCR API contracts shared by `@eigenpal/ocr-service`, clients, and tests.
 *
 * Wire shapes use snake_case to match docs/OCR_API_OPENAPI.yaml.
 */

export {
  BoundingBoxSchema,
  CONTENT_KINDS,
  ChunkProvenanceSpanSchema,
  ContentKindSchema,
  ExtractionChunkSchema,
  PAGE_BLOCK_KINDS,
  PageBlockKindSchema,
  PageBlockSchema,
  ParsedDocumentSchema,
  PointSchema,
  PolygonSchema,
  REGION_TYPES,
  RegionContentSchema,
  RegionSchema,
  RegionTypeSchema,
  type BoundingBox,
  type ChunkProvenanceSpan,
  type ContentKind,
  type ExtractionChunk,
  type PageBlock,
  type PageBlockKind,
  type ParsedDocument,
  type Point,
  type Polygon,
  type Region,
  type RegionContent,
  type RegionType,
} from './parsed-document';

export {
  DeleteFileResponseSchema,
  ExtractBatchItemSchema,
  ExtractBatchRequestSchema,
  ExtractRequestSchema,
  ExtractionJsonSchemaObjectSchema,
  OCR_MODELS,
  OPENPARSER_COMPONENT_SCHEMAS,
  OPENPARSER_ROUTE_MANIFEST,
  OcrFileIdSchema,
  OcrModelSchema,
  OpenParserParseResultSchema,
  ParseBatchItemSchema,
  ParseBatchRequestSchema,
  ParseRequestSchema,
  PublicFileSchema,
  RepairAttemptsSchema,
  getOpenParserRoute,
  type DeleteFileResponse,
  type ExtractBatchItem,
  type ExtractBatchRequest,
  type ExtractRequest,
  type OcrFileId,
  type OcrModel,
  type OpenParserComponentSchemaName,
  type OpenParserOperationId,
  type OpenParserParseResult,
  type OpenParserRoute,
  type ParseBatchItem,
  type ParseBatchRequest,
  type ParseRequest,
  type PublicFile,
} from './contracts';

export {
  OCR_OUTPUT_FORMATS,
  OcrOutputFormatSchema,
  PaddleRawProfileSchema,
  RawParseResultSchema,
  type OcrOutputFormat,
  type RawParseResult,
} from './raw-result';

export {
  EXTRACTION_ATTEMPT_KINDS,
  EXTRACTION_ATTEMPT_STATUSES,
  ExtractionAttemptKindSchema,
  ExtractionAttemptSchema,
  ExtractionAttemptStatusSchema,
  ExtractionTerminalResultSchema,
  ExtractionUsageTotalsSchema,
  LlmModelSchema,
  type ExtractionAttempt,
  type ExtractionAttemptKind,
  type ExtractionAttemptStatus,
  type ExtractionTerminalResult,
  type ExtractionUsageTotals,
  type LlmModel,
} from './extraction';

export {
  BatchChildPageSchema,
  BatchChildSummarySchema,
  BatchJobAcceptedSchema,
  BatchSummaryCountsSchema,
  ErrorBodySchema,
  ErrorResponseSchema,
  JobAcceptedSchema,
  JobFailureSchema,
  JobIdSchema,
  JobOperationSchema,
  JobProgressSchema,
  JobSchema,
  JobStatusSchema,
  OCR_JOB_OPERATIONS,
  OCR_JOB_STATUSES,
  OCR_OPENAPI_RELATIVE_PATH,
  OCR_SYNC_STATUS_CODES,
  type BatchChildPage,
  type BatchChildSummary,
  type BatchJobAccepted,
  type BatchSummaryCounts,
  type ErrorBody,
  type ErrorResponse,
  type Job,
  type JobAccepted,
  type JobFailure,
  type JobId,
  type JobOperation,
  type JobProgress,
  type JobStatus,
} from './jobs';
